### ISSUE TITLE
Reconcile cookbooks we have vs files in terraform

### ISSUE THREAD

**Issue by Xorima** [sous-chefs/terraform-github-org#134]
### Description

We do not have a 1 to 1 file for terraform vs repositories, this is so we can maintain repositories using terraform

**Comment by JohnRoesler** [comment]
@Xorima sorry to jump on your ticket, but I was bored, so went through the repos and here is what I got.


Cookbooks that don't have terraform files:
```
apache2_mod_fastcgi (new)
redisio (new)
chef-appveyor-ci
chef-stunnel
sc-chruby
sc-nxlog
mysql_database (empty repo)
sc-generator (empty repo)
```

Other repos that don't have terraform files:
```
repo-management
SublimeChef
thor-foodcritic
```

Terraform files that don't match the standard name.tf == name of repo:
```
board.tf == website?
cef_de_partie.tf, hw_cookbooks.tf == nexus, control_groups?
selinuxpolicy.tf vs selinux_policy
```

**Comment by damacus** [comment]
Awesome. I can get cracking on with these tomorrow

**Comment by damacus** [comment]
What're we missing off this one @Xorima?

**Comment by Xorima** [comment]
I only handled missing ones, have not done a full reconciliation

**Comment by Xorima** [comment]
100% of cookbooks are now in Terraform
