### ISSUE TITLE
Consistent labeling across repositories

### ISSUE THREAD

**Issue by xamebax** [sous-chefs/terraform-github-org#60]
It would be great if we had a uniform system for labeling issues. We could have Terraform define them for each repository. Proposed labels (similar to what Chef has):

- `Type: Jump-In`
- `Type: Feature Request`
- `Type: Bug`
- `Type: Documentation`
- `Type: Maintenance`
- `Priority: High`
- `Priority: Medium`
- `Priority: Low`
- `Status: Blocked`
- `Status: In Progress`
- `Status: On Hold`

**Comment by tas50** [comment]
This would be super useful. It would allow us to have a nice dashboard view of simple to fix issues similar to what Thom setup for chef.

**Comment by xamebax** [comment]
I think we maybe wouldn't need an exact 1:1 representation of all Chef label types, though :)

**Comment by damacus** [comment]
Looks like github has just added some helping pointers with the following labels: 
`
help wanted or good first issue`

**Comment by damacus** [comment]
![screen shot 2017-10-12 at 15 59 22](https://user-images.githubusercontent.com/40786/31502955-4a1aa1d2-af66-11e7-87ee-53f37e63ba0b.png)

**Comment by xamebax** [comment]
How should we go about this: add one of these to get github support or substitute one from the list above?

**Comment by damacus** [comment]
sub 

Type: Jump-In for `good first issue`
